name: Bug report
description: Report broken guidance, stale APIs, or unexpected skill behavior.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What went wrong?
      placeholder: Clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: Provide prompt, relevant code snippet, and what happened.
      placeholder: |
        Prompt:
        Code snippet:
        Output:
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should the skill have recommended or done?
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Related source or docs
      description: Link official docs or reference if available.
